version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`spoke.scrambleduser.vip`)"
      - "traefik.http.routers.app.entrypoints=http,https"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
    networks:
      - default

networks:
  default:
    external: true
    name: sksg8wogcgsk4gwcsc4c8w8c