services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - default

networks:
  default:
    external: true
    name: sksg8wogcgsk4gwcsc4c8w8c